export const itCoursesDetails = [
    {
        title: "Python Programming Fundamentals",
        overview:
            "This course provides a comprehensive introduction to Python programming, covering everything from basic syntax to advanced concepts like object-oriented programming. Python is one of the most versatile and highly demanded programming languages in the tech industry today, powering web applications, data analysis, artificial intelligence, and automation.",
        whatYouWillLearn: [
            "Understand and implement core Python syntax and concepts",
            "Work with data types, variables, loops, and conditional statements",
            "Create and use functions, modules, and packages",
            "Master object-oriented programming (OOP) principles in Python",
            "Handle errors and exceptions robustly",
            "Perform file reading and writing operations",
            "Use popular Python libraries for building fundamental projects",
            "Develop clean, readable, and highly maintainable code",
        ],
        courseHighlights: [
            "Beginner friendly learning path",
            "Practical technology skills",
            "Hands-on exercises",
            "Real-world examples",
        ],
        duration: "22 lessons (approximately 1 month)",
        lessons: [
            "Lesson 1 â€“ Introduction to Python",
            "Lesson 2 â€“ Setting Up the Environment",
            "Lesson 3 â€“ Variables and Data Types",
            "Lesson 4 â€“ Basic Operators",
            "Lesson 5 â€“ Working with Strings",
            "Lesson 6 â€“ Conditional Statements",
            "Lesson 7 â€“ Loops and Iteration",
            "Lesson 8 â€“ Lists and Tuples",
            "Lesson 9 â€“ Dictionaries and Sets",
            "Lesson 10 â€“ Functions and Scope",
            "Lesson 11 â€“ Advanced Functions",
            "Lesson 12 â€“ Modules and Packages",
            "Lesson 13 â€“ File Handling",
            "Lesson 14 â€“ Exception Handling",
            "Lesson 15 â€“ Introduction to OOP",
            "Lesson 16 â€“ Classes and Objects",
            "Lesson 17 â€“ Inheritance and Polymorphism",
            "Lesson 18 â€“ Encapsulation and Abstraction",
            "Lesson 19 â€“ Regular Expressions",
            "Lesson 20 â€“ Working with APIs",
            "Lesson 21 â€“ Best Coding Practices",
            "Lesson 22 â€“ Final Practical Application",
        ],
        certification:
            "After successfully completing all lessons, learners will receive a Nextvera Hub Certificate of Completion which can be used for professional development and career opportunities.",
    },
    {
        title: "Web Development Bootcamp",
        overview:
            "This comprehensive bootcamp takes you from an absolute beginner to a confident web developer capable of building modern, responsive websites. With the internet being the foundation of global business and communication, learning web development equips you with foundational tech skills required by startups and large corporations alike.",
        whatYouWillLearn: [
            "Structure web pages using semantic HTML5",
            "Style modern websites with CSS3 and Flexbox/Grid",
            "Add interactive elements using vanilla JavaScript",
            "Understand the Document Object Model (DOM) and browser events",
            "Build mobile-responsive layouts from scratch",
            "Use version control with Git and GitHub",
            "Implement fundamental web accessibility and SEO practices",
            "Deploy basic static websites to the internet",
        ],
        courseHighlights: [
            "Beginner friendly learning path",
            "Practical technology skills",
            "Hands-on exercises",
            "Real-world examples",
        ],
        duration: "22 lessons (approximately 1 month)",
        lessons: [
            "Lesson 1 â€“ Introduction to Web Development",
            "Lesson 2 â€“ HTML5 Structure & Semantics",
            "Lesson 3 â€“ Forms and Input Validation",
            "Lesson 4 â€“ CSS3 Basics & Selectors",
            "Lesson 5 â€“ The CSS Box Model",
            "Lesson 6 â€“ Flexbox Layout System",
            "Lesson 7 â€“ CSS Grid Architecture",
            "Lesson 8 â€“ Responsive Web Design",
            "Lesson 9 â€“ JavaScript Fundamentals",
            "Lesson 10 â€“ Variables, Data Types & Operators",
            "Lesson 11 â€“ Control Flow & Conditionals",
            "Lesson 12 â€“ JavaScript Functions",
            "Lesson 13 â€“ Arrays and Objects",
            "Lesson 14 â€“ DOM Manipulation Basics",
            "Lesson 15 â€“ Handling User Events",
            "Lesson 16 â€“ Web Animations & Transitions",
            "Lesson 17 â€“ Working with Local Storage",
            "Lesson 18 â€“ Introduction to Git",
            "Lesson 19 â€“ Managing Projects with GitHub",
            "Lesson 20 â€“ Web Accessibility Standards",
            "Lesson 21 â€“ Web Hosting & Deployment",
            "Lesson 22 â€“ Final Practical Application",
        ],
        certification:
            "After successfully completing all lessons, learners will receive a Nextvera Hub Certificate of Completion which can be used for professional development and career opportunities.",
    },
    {
        title: "Cybersecurity Essentials",
        overview:
            "This course introduces the core principles of cybersecurity, teaching you how to protect networks, devices, and data from unauthorized access or criminal use. In an increasingly digital world marked by rising cyber threats, understanding how to secure systems is a mission-critical skill for any IT professional.",
        whatYouWillLearn: [
            "Identify common cybersecurity threats and vulnerabilities",
            "Understand the principles of network security and firewalls",
            "Implement basic encryption and cryptography techniques",
            "Defend against social engineering, phishing, and malware attacks",
            "Apply secure password and authentication management protocols",
            "Analyze network traffic for suspicious activities",
            "Understand risk management and incident response frameworks",
            "Secure personal and corporate devices effectively",
        ],
        courseHighlights: [
            "Beginner friendly learning path",
            "Practical technology skills",
            "Hands-on exercises",
            "Real-world examples",
        ],
        duration: "22 lessons (approximately 1 month)",
        lessons: [
            "Lesson 1 â€“ Introduction to Cybersecurity",
            "Lesson 2 â€“ Understanding the Threat Landscape",
            "Lesson 3 â€“ Malware and Ransomware Basics",
            "Lesson 4 â€“ Social Engineering & Phishing",
            "Lesson 5 â€“ Network Security Fundamentals",
            "Lesson 6 â€“ Firewalls and IDS/IPS",
            "Lesson 7 â€“ Introduction to Cryptography",
            "Lesson 8 â€“ Public and Private Keys",
            "Lesson 9 â€“ Password Management & Policy",
            "Lesson 10 â€“ Multi-Factor Authentication (MFA)",
            "Lesson 11 â€“ Web Application Securities",
            "Lesson 12 â€“ Securing Mobile Devices",
            "Lesson 13 â€“ Wireless Network Protection",
            "Lesson 14 â€“ Operating System Hardening",
            "Lesson 15 â€“ Access Control Guidelines",
            "Lesson 16 â€“ Incident Response Planning",
            "Lesson 17 â€“ Risk Assessment Methodologies",
            "Lesson 18 â€“ Basic Traffic Analysis",
            "Lesson 19 â€“ Data Privacy Laws & Ethics",
            "Lesson 20 â€“ Cloud Security Concepts",
            "Lesson 21 â€“ Creating a Security Culture",
            "Lesson 22 â€“ Final Practical Application",
        ],
        certification:
            "After successfully completing all lessons, learners will receive a Nextvera Hub Certificate of Completion which can be used for professional development and career opportunities.",
    },
    {
        title: "Cloud Computing with AWS",
        overview:
            "This course acts as a gateway into cloud computing by focusing on Amazon Web Services (AWS), the world's leading cloud platform. As organizations move away from traditional hardware servers to scalable, flexible, and cost-effective cloud architectures, navigating and leveraging AWS is an indispensable asset for developers and IT administrators.",
        whatYouWillLearn: [
            "Understand core cloud computing concepts (IaaS, PaaS, SaaS)",
            "Navigate the AWS Management Console securely",
            "Deploy scalable virtual machines using Amazon EC2",
            "Manage scalable cloud storage using Amazon S3",
            "Set up Virtual Private Clouds (VPC) for network isolation",
            "Design reliable Identity and Access Management (IAM) policies",
            "Implement basic load balancing and auto-scaling",
            "Monitor AWS resource usage and manage billing limits",
        ],
        courseHighlights: [
            "Beginner friendly learning path",
            "Practical technology skills",
            "Hands-on exercises",
            "Real-world examples",
        ],
        duration: "22 lessons (approximately 1 month)",
        lessons: [
            "Lesson 1 â€“ Introduction to Cloud Computing",
            "Lesson 2 â€“ Overview of the AWS Ecosystem",
            "Lesson 3 â€“ AWS Global Infrastructure",
            "Lesson 4 â€“ Navigating the AWS Console",
            "Lesson 5 â€“ Identity and Access Management",
            "Lesson 6 â€“ IAM Roles and Policies",
            "Lesson 7 â€“ Amazon Elastic Compute Cloud (EC2)",
            "Lesson 8 â€“ EC2 Instance Types and Pricing",
            "Lesson 9 â€“ Amazon Simple Storage Service (S3)",
            "Lesson 10 â€“ S3 Buckets and Object Security",
            "Lesson 11 â€“ Introduction to Amazon VPC",
            "Lesson 12 â€“ Subnets, Gateways, and Route Tables",
            "Lesson 13 â€“ Security Groups and Network ACLs",
            "Lesson 14 â€“ Elastic Load Balancing (ELB)",
            "Lesson 15 â€“ Auto Scaling Groups",
            "Lesson 16 â€“ Managed Databases with Amazon RDS",
            "Lesson 17 â€“ NoSQL Databases with DynamoDB",
            "Lesson 18 â€“ Route 53 and DNS Management",
            "Lesson 19 â€“ CloudWatch Monitoring",
            "Lesson 20 â€“ AWS Billing and Cost Management",
            "Lesson 21 â€“ AWS Shared Responsibility Model",
            "Lesson 22 â€“ Final Practical Application",
        ],
        certification:
            "After successfully completing all lessons, learners will receive a Nextvera Hub Certificate of Completion which can be used for professional development and career opportunities.",
    },
    {
        title: "Data Structures & Algorithms",
        overview:
            "This crucial course dives deep into understanding data structures and algorithms, which form the bedrock of efficient software design. The ability to write optimized code and design clever algorithmic solutions separates average programmers from great software engineers, and is a key requirement in most technical interviews.",
        whatYouWillLearn: [
            "Analyze algorithm efficiency using Big O Notation",
            "Implement and manage Arrays, Linked Lists, and Stacks",
            "Understand and utilize Queues, Hash Tables, and Trees",
            "Traverse complex Graphs and implement search strategies",
            "Write efficient sorting and searching algorithms",
            "Utilize recursion effectively for problem-solving",
            "Identify patterns for dynamic programming and greedy algorithms",
            "Tackle complex real-world software engineering challenges",
        ],
        courseHighlights: [
            "Beginner friendly learning path",
            "Practical technology skills",
            "Hands-on exercises",
            "Real-world examples",
        ],
        duration: "22 lessons (approximately 1 month)",
        lessons: [
            "Lesson 1 â€“ Introduction to Algorithms",
            "Lesson 2 â€“ Big O Notation and Time Complexity",
            "Lesson 3 â€“ Space Complexity Analysis",
            "Lesson 4 â€“ Array Fundamentals",
            "Lesson 5 â€“ Singly and Doubly Linked Lists",
            "Lesson 6 â€“ Stacks and Last-In-First-Out Logic",
            "Lesson 7 â€“ Queues and First-In-First-Out Logic",
            "Lesson 8 â€“ Understanding Hash Tables",
            "Lesson 9 â€“ Collision Resolution Strategies",
            "Lesson 10 â€“ Recursion Fundamentals",
            "Lesson 11 â€“ Basic Sorting Algorithms",
            "Lesson 12 â€“ Quick Sort and Merge Sort",
            "Lesson 13 â€“ Linear and Binary Search",
            "Lesson 14 â€“ Introduction to Trees",
            "Lesson 15 â€“ Binary Search Trees",
            "Lesson 16 â€“ Tree Traversal Methods",
            "Lesson 17 â€“ Priority Queues and Heaps",
            "Lesson 18 â€“ Graph Theory Basics",
            "Lesson 19 â€“ Graph Search: BFS and DFS",
            "Lesson 20 â€“ Greedy Algorithms Concepts",
            "Lesson 21 â€“ Introduction to Dynamic Programming",
            "Lesson 22 â€“ Final Practical Application",
        ],
        certification:
            "After successfully completing all lessons, learners will receive a Nextvera Hub Certificate of Completion which can be used for professional development and career opportunities.",
    }
];
export const itCoursesDetailsPart2 = [
    {
        title: "Mobile App Development",
        overview:
            "Dive into the booming world of mobile applications by learning how to build rich, dynamic, and native-feeling apps for both iOS and Android. Mobile devices are now the primary way people access the internet and services, making mobile development one of the most highly sought-after capabilities for modern tech teams.",
        whatYouWillLearn: [
            "Understand the fundamentals of mobile application architecture",
            "Design intuitive, user-friendly mobile interfaces and experiences",
            "Develop cross-platform mobile apps using a single codebase",
            "Manage app state efficiently using modern frameworks",
            "Connect mobile applications to RESTful APIs and backend services",
            "Implement local storage and offline capabilities",
            "Navigate mobile device features such as cameras and location",
            "Prepare and deploy apps to the Apple App Store and Google Play",
        ],
        courseHighlights: [
            "Beginner friendly learning path",
            "Practical technology skills",
            "Hands-on exercises",
            "Real-world examples",
        ],
        duration: "22 lessons (approximately 1 month)",
        lessons: [
            "Lesson 1 â€“ Introduction to Mobile App Development",
            "Lesson 2 â€“ Setting Up the Development Environment",
            "Lesson 3 â€“ Introduction to the Framework",
            "Lesson 4 â€“ Basic App Architecture",
            "Lesson 5 â€“ Working with Layouts",
            "Lesson 6 â€“ UI Components and Styling",
            "Lesson 7 â€“ Handling User Input",
            "Lesson 8 â€“ Navigation and Routing",
            "Lesson 9 â€“ State Management Basics",
            "Lesson 10 â€“ Advanced State Handling",
            "Lesson 11 â€“ Fetching Data from APIs",
            "Lesson 12 â€“ Handling Asynchronous Operations",
            "Lesson 13 â€“ Managing Local Data Storage",
            "Lesson 14 â€“ Utilizing the Device Camera",
            "Lesson 15 â€“ Accessing Geolocation APIs",
            "Lesson 16 â€“ Push Notifications",
            "Lesson 17 â€“ App Permissions and Security",
            "Lesson 18 â€“ Troubleshooting and Debugging Apps",
            "Lesson 19 â€“ App Performance Optimization",
            "Lesson 20 â€“ Preparing for App Store Release",
            "Lesson 21 â€“ Google Play Store Deployment",
            "Lesson 22 â€“ Final Practical Application",
        ],
        certification:
            "After successfully completing all lessons, learners will receive a Nextvera Hub Certificate of Completion which can be used for professional development and career opportunities.",
    },
    {
        title: "DevOps & CI/CD Practices",
        overview:
            "This course bridges the gap between software development and IT operations, teaching the core DevOps practices that enable organizations to deliver applications rapidly. Continuous Integration and Continuous Deployment (CI/CD) pipelines dramatically improve software quality and reduce deployment times, making DevOps engineers highly valuable in any modern software project.",
        whatYouWillLearn: [
            "Understand the principles and culture of DevOps",
            "Utilize Version Control effectively in a team environment",
            "Set up automated build and test environments",
            "Design and construct reliable CI/CD pipelines",
            "Automate infrastructure provisioning using Infrastructure as Code",
            "Monitor application performance and system health",
            "Implement secure deployment strategies like blue-green deployments",
            "Containerize applications and manage orchestration",
        ],
        courseHighlights: [
            "Beginner friendly learning path",
            "Practical technology skills",
            "Hands-on exercises",
            "Real-world examples",
        ],
        duration: "22 lessons (approximately 1 month)",
        lessons: [
            "Lesson 1 â€“ Introduction to DevOps Culture",
            "Lesson 2 â€“ Linux Command Line Basics",
            "Lesson 3 â€“ Shell Scripting for Automation",
            "Lesson 4 â€“ Advanced Version Control with Git",
            "Lesson 5 â€“ Continuous Integration Concepts",
            "Lesson 6 â€“ Containerization with Docker",
            "Lesson 7 â€“ Docker Compose for Multi-Container Apps",
            "Lesson 8 â€“ Introduction to CI/CD Tools",
            "Lesson 9 â€“ Building a Basic CI Pipeline",
            "Lesson 10 â€“ Automated Testing in CI",
            "Lesson 11 â€“ Continuous Deployment Concepts",
            "Lesson 12 â€“ Constructing a CD Pipeline",
            "Lesson 13 â€“ Infrastructure as Code (IaC) Basics",
            "Lesson 14 â€“ Provisioning with Terraform",
            "Lesson 15 â€“ Configuration Management with Ansible",
            "Lesson 16 â€“ Introduction to Kubernetes",
            "Lesson 17 â€“ Application Monitoring and Logging",
            "Lesson 18 â€“ Incident Management and Alerting",
            "Lesson 19 â€“ Secure DevOps (DevSecOps)",
            "Lesson 20 â€“ Release Management Strategies",
            "Lesson 21 â€“ Scaling DevOps Practices",
            "Lesson 22 â€“ Final Practical Application",
        ],
        certification:
            "After successfully completing all lessons, learners will receive a Nextvera Hub Certificate of Completion which can be used for professional development and career opportunities.",
    },
    {
        title: "Networking and System Administration",
        overview:
            "Gain the foundational knowledge needed to construct, manage, and maintain robust IT networks and operating systems. Every organization relies on secure and stable networks to function; this course provides the critical hands-on knowledge to analyze, configure, and troubleshoot corporate infrastructure.",
        whatYouWillLearn: [
            "Understand the OSI model, TCP/IP, and networking fundamentals",
            "Configure and manage networking hardware like routers and switches",
            "Implement robust network security protocols",
            "Perform essential system administration tasks on Linux and Windows",
            "Manage user accounts, permissions, and group policies",
            "Monitor network traffic and troubleshoot connectivity issues",
            "Perform routine system updates, patches, and backups",
            "Design scalable network architectures for modern enterprises",
        ],
        courseHighlights: [
            "Beginner friendly learning path",
            "Practical technology skills",
            "Hands-on exercises",
            "Real-world examples",
        ],
        duration: "22 lessons (approximately 1 month)",
        lessons: [
            "Lesson 1 â€“ Introduction to Computer Networks",
            "Lesson 2 â€“ The OSI and TCP/IP Models",
            "Lesson 3 â€“ IP Addressing and Subnetting",
            "Lesson 4 â€“ Network Topologies and Media",
            "Lesson 5 â€“ Introduction to Switching",
            "Lesson 6 â€“ VLANs and Inter-VLAN Routing",
            "Lesson 7 â€“ Introduction to Routing",
            "Lesson 8 â€“ Access Control Lists (ACLs)",
            "Lesson 9 â€“ Wireless Networking Standards",
            "Lesson 10 â€“ Network Troubleshooting Methodologies",
            "Lesson 11 â€“ Introduction to System Administration",
            "Lesson 12 â€“ Operating System Installation",
            "Lesson 13 â€“ File Systems and Storage Management",
            "Lesson 14 â€“ User and Group Management",
            "Lesson 15 â€“ Directory Services Fundamentals",
            "Lesson 16 â€“ Active Directory Configuration",
            "Lesson 17 â€“ Linux Administration Basics",
            "Lesson 18 â€“ System Performance Monitoring",
            "Lesson 19 â€“ Backup and Disaster Recovery",
            "Lesson 20 â€“ Network Services (DNS, DHCP)",
            "Lesson 21 â€“ Server Virtualization",
            "Lesson 22 â€“ Final Practical Application",
        ],
        certification:
            "After successfully completing all lessons, learners will receive a Nextvera Hub Certificate of Completion which can be used for professional development and career opportunities.",
    },
    {
        title: "Database Design & SQL",
        overview:
            "Data is the new oil, and databases are the refineries. This course teaches the essential skills required to design structured, efficient relational databases and query them successfully using SQL. Understanding how to store, retrieve, and manipulate data securely is vital for backend developers, data analysts, and IT professionals.",
        whatYouWillLearn: [
            "Design normalized relational databases from scratch",
            "Write basic to advanced SQL queries to manipulate data",
            "Use JOIN operations to combine data from multiple tables",
            "Create and interpret Entity-Relationship Diagrams (ERDs)",
            "Implement database constraints to ensure data integrity",
            "Optimize query performance using indexes",
            "Write stored procedures and database triggers",
            "Understand fundamental differences between SQL and NoSQL",
        ],
        courseHighlights: [
            "Beginner friendly learning path",
            "Practical technology skills",
            "Hands-on exercises",
            "Real-world examples",
        ],
        duration: "22 lessons (approximately 1 month)",
        lessons: [
            "Lesson 1 â€“ Introduction to Databases",
            "Lesson 2 â€“ Data Modeling Principles",
            "Lesson 3 â€“ Entity-Relationship Diagrams",
            "Lesson 4 â€“ Normalization (1NF, 2NF, 3NF)",
            "Lesson 5 â€“ Installing an RDBMS Environment",
            "Lesson 6 â€“ Relational Database Architecture",
            "Lesson 7 â€“ Introduction to SQL Syntax",
            "Lesson 8 â€“ Data Definition Language (DDL)",
            "Lesson 9 â€“ Data Manipulation Language (DML)",
            "Lesson 10 â€“ Simple SELECT Queries",
            "Lesson 11 â€“ Filtering and Sorting Data",
            "Lesson 12 â€“ SQL Aggregate Functions",
            "Lesson 13 â€“ GROUP BY and HAVING Clauses",
            "Lesson 14 â€“ Understanding Database JOINs",
            "Lesson 15 â€“ Advanced JOIN Techniques",
            "Lesson 16 â€“ Subqueries and Nested Queries",
            "Lesson 17 â€“ Views and Common Table Expressions",
            "Lesson 18 â€“ SQL Constraints and Data Integrity",
            "Lesson 19 â€“ Introduction to Stored Procedures",
            "Lesson 20 â€“ Triggers and Functions",
            "Lesson 21 â€“ Indexes and Query Optimization",
            "Lesson 22 â€“ Final Practical Application",
        ],
        certification:
            "After successfully completing all lessons, learners will receive a Nextvera Hub Certificate of Completion which can be used for professional development and career opportunities.",
    },
    {
        title: "Ethical Hacking and Penetration Testing",
        overview:
            "Step into the shoes of a hacker to learn how to secure systems against them. This course teaches the methodologies of penetration testing and ethical hacking, equipping you with the practical skills needed to uncover vulnerabilities in networks, applications, and operating systems before malicious actors exploit them.",
        whatYouWillLearn: [
            "Understand the ethical hacking methodology and legal constraints",
            "Conduct passive and active footprinting and reconnaissance",
            "Perform network scanning to identify open ports and services",
            "Carry out vulnerability assessments on target systems",
            "Execute safe system hacking techniques and payload delivery",
            "Analyze and exploit common web application vulnerabilities",
            "Understand and intercept network traffic (Sniffing)",
            "Document assessment findings in detailed penetration test reports",
        ],
        courseHighlights: [
            "Beginner friendly learning path",
            "Practical technology skills",
            "Hands-on exercises",
            "Real-world examples",
        ],
        duration: "22 lessons (approximately 1 month)",
        lessons: [
            "Lesson 1 â€“ Introduction to Ethical Hacking",
            "Lesson 2 â€“ Cyber Law and Ethics",
            "Lesson 3 â€“ Setting Up Your Penetration Testing Lab",
            "Lesson 4 â€“ Introduction to Kali Linux",
            "Lesson 5 â€“ Information Gathering (Reconnaissance)",
            "Lesson 6 â€“ Footprinting Methodologies",
            "Lesson 7 â€“ Network Scanning with Nmap",
            "Lesson 8 â€“ Enumeration Techniques",
            "Lesson 9 â€“ Vulnerability Assessment Principles",
            "Lesson 10 â€“ System Hacking Methodologies",
            "Lesson 11 â€“ Password Cracking Techniques",
            "Lesson 12 â€“ Maintaining System Access",
            "Lesson 13 â€“ Malware Analysis Fundamentals",
            "Lesson 14 â€“ Sniffing and Spoofing Tools",
            "Lesson 15 â€“ Social Engineering Tactics",
            "Lesson 16 â€“ Web Server Weaknesses",
            "Lesson 17 â€“ Web Application Enumeration",
            "Lesson 18 â€“ SQL Injection Attacks",
            "Lesson 19 â€“ Cross-Site Scripting (XSS)",
            "Lesson 20 â€“ Wireless Network Penetration",
            "Lesson 21 â€“ Report Writing and Documentation",
            "Lesson 22 â€“ Final Practical Application",
        ],
        certification:
            "After successfully completing all lessons, learners will receive a Nextvera Hub Certificate of Completion which can be used for professional development and career opportunities.",
    }
];
