import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { Document, Types } from 'mongoose';

export type VideoDocument = Video & Document;

// ─── Sub-schemas ─────────────────────────────────────────────────────────────

/** Raw file information stored in S3 (raw/original bucket). */
@Schema({ _id: false })
export class VideoOriginal {
  /** S3 object key for the raw uploaded file, e.g. "originals/uuid/lecture.mp4" */
  @Prop({ required: true })
  key: string;

  @Prop({ default: 0 })
  size_bytes: number;

  /** File MIME type or extension, e.g. "video/mp4" */
  @Prop()
  format: string;

  @Prop({ default: 0 })
  duration_seconds: number;
}

/** One HLS quality rendition produced by MediaConvert. */
@Schema({ _id: false })
export class VideoQuality {
  /** Resolution label, e.g. "360p", "720p" */
  @Prop({
    type: String,
    enum: ['360p', '480p', '720p', '1080p'],
    required: true,
  })
  resolution: string;

  /** Target bitrate in bps (e.g. 800000 for 800 kbps) */
  @Prop({ default: 0 })
  bitrate: number;

  /**
   * CloudFront URL for the per-rendition m3u8 playlist.
   * Constructed from CLOUDFRONT_VIDEO_DOMAIN + S3 key path.
   */
  @Prop()
  url: string;
}

/** Processed/transcoded video artefacts – populated after MediaConvert succeeds. */
@Schema({ _id: false })
export class VideoProcessed {
  /**
   * Processing lifecycle state.
   * pending    → just uploaded, awaiting queue
   * processing → MediaConvert job running
   * completed  → HLS segments ready, URLs populated
   * failed     → transcode error
   */
  @Prop({
    type: String,
    enum: ['pending', 'processing', 'completed', 'failed'],
    default: 'pending',
  })
  status: string;

  /**
   * CloudFront URL for the HLS master playlist (master.m3u8).
   * Null until status = 'completed'.
   */
  @Prop({ type: String, default: null })
  manifest_url: string | null;

  @Prop({ type: [VideoQuality], default: [] })
  qualities: VideoQuality[];

  /** Thumbnail image URL served via CloudFront. */
  @Prop({ type: String, default: null })
  thumbnail_url: string | null;

  /**
   * VTT sprite-sheet for timeline thumbnail scrubbing.
   * Null until processing is complete.
   */
  @Prop({ type: String, default: null })
  thumbnails_vtt: string | null;
}

/** A caption/subtitle track for a specific language. */
@Schema({ _id: false })
export class VideoCaption {
  /** BCP-47 language tag, e.g. "en", "hi", "fr" */
  @Prop({ required: true })
  language: string;

  /** URL of the WebVTT or SRT file (served via CloudFront). */
  @Prop({ required: true })
  url: string;

  /** True if generated by an automated transcription service (e.g. Amazon Transcribe). */
  @Prop({ default: false })
  auto_generated: boolean;
}

// ─── Root document ────────────────────────────────────────────────────────────

@Schema({ timestamps: { createdAt: 'created_at', updatedAt: 'updated_at' } })
export class Video {
  /**
   * MongoDB ObjectId of the course this video belongs to.
   * Mirrors the `course_id` stored in the Courses collection.
   */
  @Prop({ type: Types.ObjectId, required: true, index: true })
  course_id: Types.ObjectId;

  /**
   * MongoDB ObjectId of the specific lesson that embeds this video.
   * Corresponds to `curriculum.sections[].lessons[].content.video_id`.
   */
  @Prop({ type: Types.ObjectId, index: true })
  lesson_id: Types.ObjectId;

  /**
   * UUID of the teacher (PostgreSQL `users.id`) who uploaded this video.
   * Allows ownership checks without a cross-DB join on every request.
   */
  @Prop({ required: true, index: true })
  teacher_id: string;

  // ── Raw upload data ──────────────────────────────────────────────────────

  @Prop({ type: VideoOriginal, required: true })
  original: VideoOriginal;

  // ── Processed / HLS data ─────────────────────────────────────────────────

  @Prop({ type: VideoProcessed, default: () => ({}) })
  processed: VideoProcessed;

  // ── Captions ─────────────────────────────────────────────────────────────

  @Prop({ type: [VideoCaption], default: [] })
  captions: VideoCaption[];

  // ── Engagement stats ──────────────────────────────────────────────────────

  /** Total number of individual play events. */
  @Prop({ default: 0 })
  views: number;

  /** Cumulative watch time in seconds across all viewers. */
  @Prop({ default: 0 })
  watch_time_total: number;

  /**
   * Timestamp set when MediaConvert finishes transcoding.
   * Null while status ≠ 'completed'.
   */
  @Prop({ type: Date, default: null })
  processed_at: Date | null;

  // Injected by timestamps option:
  created_at?: Date;
  updated_at?: Date;
}

export const VideoSchema = SchemaFactory.createForClass(Video);

// Compound index for listing a teacher's videos quickly
VideoSchema.index({ teacher_id: 1, 'processed.status': 1 });
// Useful for enrollment/playback access checks: fetch video by course + lesson
VideoSchema.index({ course_id: 1, lesson_id: 1 });
